import { useAuth } from '../context/AuthContext.jsx';
import { formatDate, formatINR } from '../utils/formatters.js';
import { Link, useNavigate } from 'react-router-dom';
import { Activity, ArrowRight, LockKeyhole, ShieldCheck } from 'lucide-react';

export default function Profile() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();

  async function signOut() {
    await logout();
    navigate('/login', { replace: true });
  }

  return (
    <div className="page-stack">
      <div className="page-heading"><div><span className="eyebrow">ACCOUNT SETTINGS</span><h1>Your paper account.</h1><p>A private space to practice with simulated market data.</p></div></div>
      <section className="profile-hero panel"><div className="profile-hero__identity"><span className="avatar avatar--large">{user?.name?.slice(0, 1)?.toUpperCase() || 'U'}</span><div><span className="eyebrow">PAPER-TRADING MEMBER</span><h2>{user?.name}</h2><p>{user?.email}</p></div></div><span className="tag tag--simulated"><span /> practice account</span></section>
      <section className="profile-grid"><article className="panel profile-detail-panel"><div className="panel-heading"><div><span className="eyebrow">ACCOUNT DETAILS</span><h2>Profile</h2></div><span className="profile-detail-icon"><Activity size={17} /></span></div><dl className="profile-details"><div><dt>Full name</dt><dd>{user?.name || '—'}</dd></div><div><dt>Email address</dt><dd>{user?.email || '—'}</dd></div><div><dt>Member since</dt><dd>{formatDate(user?.createdAt)}</dd></div><div><dt>Available virtual cash</dt><dd className="profile-cash">{formatINR(user?.virtualBalance)}</dd></div></dl><Link className="text-link" to="/portfolio">View your portfolio <ArrowRight size={14} /></Link></article>
        <article className="panel profile-security-panel"><div className="panel-heading"><div><span className="eyebrow">SECURITY & TRANSPARENCY</span><h2>Practice safely</h2></div><ShieldCheck size={19} className="positive" /></div><div className="security-point"><LockKeyhole size={16} /><div><strong>Private sign-in</strong><span>Your password is hashed before it is stored. Authentication is required for personal holdings, trades, and watchlists.</span></div></div><div className="security-point"><Activity size={16} /><div><strong>Simulated market</strong><span>Prices are generated by a controlled mock engine. No live exchange feed or broker connection is used.</span></div></div><div className="security-point"><span className="rupee-icon">₹</span><div><strong>Virtual money only</strong><span>Account balances are fictional INR values with no cash or investment value. No real-money order is ever placed.</span></div></div><button className="button button--subtle profile-signout" onClick={signOut}>Sign out</button></article></section>
    </div>
  );
}
