import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowDownRight, ArrowUpRight, BookmarkPlus, Info, TrendingUp } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { marketService } from '../services/marketService.js';
import { useMarketData } from '../context/MarketContext.jsx';
import { formatDate, formatINR, formatPercent } from '../utils/formatters.js';
import BuySellModal from '../components/BuySellModal.jsx';
import PriceChart from '../components/PriceChart.jsx';
import LoadingSpinner from '../components/LoadingSpinner.jsx';
import StateBlock from '../components/StateBlock.jsx';
import WatchlistButton from '../components/WatchlistButton.jsx';

const periods = ['1D', '1W', '1M', '6M', '1Y'];

export default function StockDetails() {
  const { symbol: routeSymbol } = useParams();
  const symbol = decodeURIComponent(routeSymbol || '').toUpperCase();
  const { prices } = useMarketData();
  const [period, setPeriod] = useState('1M');
  const [stock, setStock] = useState(null);
  const [holding, setHolding] = useState(null);
  const [watched, setWatched] = useState(false);
  const [tradeSide, setTradeSide] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const load = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const [stockData, portfolio, watchlist] = await Promise.all([
        marketService.getStock(symbol, period), marketService.getPortfolio(), marketService.getWatchlist(),
      ]);
      setStock(stockData);
      setHolding(portfolio.holdings.find((item) => item.symbol === symbol) || null);
      setWatched(watchlist.some((item) => item.symbol === symbol));
    } catch (requestError) {
      setError(requestError.message);
    } finally { setLoading(false); }
  }, [symbol, period]);

  useEffect(() => { load(); }, [load]);

  const live = prices[symbol];
  const currentPrice = live?.currentPrice ?? stock?.currentPrice ?? 0;
  const change = live?.change ?? stock?.change ?? 0;
  const changePercent = live?.changePercent ?? stock?.changePercent ?? 0;
  const history = useMemo(() => {
    if (!stock?.priceHistory?.length) return [];
    const rows = [...stock.priceHistory];
    if (live?.updatedAt) {
      const last = rows.at(-1);
      if (!last || new Date(live.updatedAt).getTime() > new Date(last.time).getTime()) rows.push({ time: live.updatedAt, price: currentPrice });
    }
    return rows;
  }, [stock, live, currentPrice]);

  async function toggleWatch() {
    try {
      if (watched) await marketService.removeWatchlist(symbol);
      else await marketService.addWatchlist(symbol);
      setWatched(!watched);
    } catch (requestError) { setError(requestError.message); }
  }

  if (loading) return <LoadingSpinner label={`Loading ${symbol} simulated details…`} />;
  if (error && !stock) return <StateBlock kind="error" title="Stock details are unavailable" description={error} action={<Link className="button button--subtle" to="/stocks">Back to markets</Link>} />;
  if (!stock) return <StateBlock title="Stock not found" description={`No simulated stock is available for ${symbol}.`} action={<Link className="button button--subtle" to="/stocks">Browse markets</Link>} />;

  const positive = change >= 0;
  const ChangeIcon = positive ? ArrowUpRight : ArrowDownRight;
  return (
    <div className="page-stack">
      <Link className="back-link" to="/stocks"><ArrowLeft size={15} /> Back to markets</Link>
      {error && <p className="inline-alert" role="alert">{error}</p>}
      <section className="detail-hero panel">
        <div className="detail-identity"><span className="ticker-avatar ticker-avatar--large">{symbol.slice(0, 1)}</span><div><span className="eyebrow">NSE SCENARIO · SIMULATED</span><h1>{symbol}</h1><p>{stock.companyName}</p></div></div>
        <div className="detail-price"><strong>{formatINR(currentPrice)}</strong><span className={positive ? 'positive' : 'negative'}><ChangeIcon size={15} /> {formatINR(change)} ({formatPercent(changePercent, { signed: true })})</span><small>Updated {formatDate(live?.updatedAt || stock.updatedAt, { hour: '2-digit', minute: '2-digit', second: '2-digit' })}</small></div>
        <div className="detail-actions"><button className="button button--primary" onClick={() => setTradeSide('BUY')}>Buy <ArrowDownRight size={15} /></button><button className="button button--subtle" disabled={!holding} onClick={() => setTradeSide('SELL')}>Sell <ArrowUpRight size={15} /></button><WatchlistButton active={watched} onClick={toggleWatch} /></div>
      </section>
      <div className="sim-disclosure"><Info size={16} /><span>Practice data only</span> These prices are generated by a mock simulator. They are not live exchange quotes or investment advice.</div>
      <section className="panel detail-chart-panel">
        <div className="panel-heading"><div><span className="eyebrow">SIMULATED PRICE HISTORY</span><h2>{stock.companyName} <small>{symbol}</small></h2></div><div className="period-switcher" role="group" aria-label="Chart period">{periods.map((item) => <button key={item} className={item === period ? 'active' : ''} onClick={() => setPeriod(item)}>{item}</button>)}</div></div>
        <div className="detail-chart-price"><strong>{formatINR(currentPrice)}</strong><span className={positive ? 'positive' : 'negative'}><ChangeIcon size={14} />{formatPercent(changePercent, { signed: true })}</span></div>
        <PriceChart data={history} id={`stock-${symbol}`} height={310} />
        <div className="chart-footer"><span><i className="legend-dot" /> Practice price · INR</span><span><TrendingUp size={13} /> Simulated updates every few seconds</span></div>
      </section>
      <section className="detail-facts-grid">
        {[['Open', stock.open], ['High', live?.high ?? stock.high], ['Low', live?.low ?? stock.low], ['Previous close', stock.previousClose], ['Volume', new Intl.NumberFormat('en-IN').format(live?.volume ?? stock.volume)], ['Exchange scenario', 'NSE · mock']].map(([label, value]) => <article className="fact-card" key={label}><span>{label}</span><strong>{typeof value === 'number' ? formatINR(value) : value}</strong></article>)}
      </section>
      {holding && <div className="holding-callout"><BookmarkPlus size={16} /><span>You hold {holding.quantity} {holding.quantity === 1 ? 'share' : 'shares'} of {symbol} in your paper portfolio.</span><Link to="/portfolio">View portfolio</Link></div>}
      {tradeSide && <BuySellModal stock={{ ...stock, currentPrice }} side={tradeSide} availableShares={holding?.quantity || 0} onClose={() => setTradeSide('')} onComplete={load} />}
    </div>
  );
}
